In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("F:\\New folder\\ML\\CSV files\\covid_toy.csv")
df.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df=df.dropna()

In [6]:
df=df.drop(columns=['age','fever'])

In [7]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [9]:
from sklearn.preprocessing import OneHotEncoder

## get_dummins method

In [10]:
df.shape

(90, 4)

In [12]:
p = pd.get_dummies(df,columns=['gender','cough','city','has_covid'])

In [13]:
p.shape

(90, 10)

In [15]:
p = pd.get_dummies(df,columns=['gender','cough','city','has_covid'], drop_first=True)

In [16]:
p.shape

(90, 6)

In [17]:
ohe=OneHotEncoder(drop='first', sparse=False,dtype=np.int32)

In [20]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [21]:
df_new.shape

(90, 6)

In [24]:
p

gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai  \
0             1             0           0             1            0   
1             1             0           1             0            0   
2             1             0           1             0            0   
3             0             0           0             1            0   
4             0             0           0             0            1   
..          ...           ...         ...           ...          ...   
95            0             0           0             0            0   
96            0             1           0             1            0   
97            0             0           0             0            0   
98            0             1           0             0            1   
99            0             1           0             1            0   

    has_covid_Yes  
0               0  
1               1  
2               0  
3               0  
4               0  
..            ...  
95              0  
96              1  
97              0  
98              0  
99              1  

[90 rows x 6 columns]

In [23]:
df_new.shape

(90, 6)

In [25]:
df_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
 

## Column Transformer

In [32]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [33]:
df=pd.read_csv("F:\\New folder\\ML\\CSV files\\covid_toy.csv")
df.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [34]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [35]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2
                                            )

In [38]:
x_train

age  gender  fever   cough       city
76   80    Male  100.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
64   42    Male  104.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
41   82    Male    NaN    Mild    Kolkata
24   13  Female  100.0  Strong    Kolkata
14   51    Male  104.0    Mild  Bangalore
59    6  Female  104.0    Mild    Kolkata
66   51    Male  104.0    Mild    Kolkata

[80 rows x 5 columns]

## Manually Type Output

In [41]:
# adding simple imputer to fever column
si = SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever=si.fit_transform(x_test[['fever']])
print(x_train_fever.shape)
print(x_test_fever.shape)

(80, 1)
(20, 1)


In [45]:
# Ordinary Encoding on --> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough=oe.fit_transform(x_test[['cough']])
print(x_train_cough.shape)
print(x_test_cough.shape)

(80, 1)
(20, 1)


In [48]:
# OneHotEncoding --> Gender , city
ohe = OneHotEncoder(drop='first',sparse=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city=ohe.fit_transform(x_train[['gender','city']])
print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(80, 4)


C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [49]:
# Extracting age
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

print(x_train_age.shape)
print(x_test_age.shape)

(80, 1)
(20, 1)


In [51]:
x_train_transform=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough), axis=1)

In [53]:
x_train_transform.shape

(80, 7)

In [61]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), # in fever column we will fill missing value with help of SI
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [62]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1', SimpleImputer(), ['fever']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('tnf3',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['gender', 'city'])])

In [63]:
transformer.fit_transform(x_train).shape

C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [64]:
transformer.fit_transform(x_test).shape

C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(20, 7)

## Function Trasformer

By using function trasformer we can pass  a condition on our array

In [66]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a data set
x=np.array([[1,2],[3,4]])

# define the transformation function 
log_transform=FunctionTransformer(np.log1p) #log1p function

# apply the transformation to the data set
x_transformed=log_transform.transform(x)

print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


## Types of Function transformer in machine learning

In [68]:
# Example 2

# define a custom feature engineering function
def my_feature_engineering(x):
    return np.hstack((x,x**x))

# create a function transformer to apply the custom function 

custom_transformer = FunctionTransformer(my_feature_engineering)

# apply transformer to the output data

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[  1   2   1   4]
 [  3   4  27 256]]


In [69]:
# Example 3
# scaling 
def my_scaling(x):
    return x/np.max(x)
custom_transformer = FunctionTransformer(my_scaling)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [73]:
# Example 4 

# data cleaning

x=np.array([[1,2],[3,np.nan]]),
def my_cleaning(x):
    x[np.nan(x)]=0
    return x
custom_transformer = FunctionTransformer(my_cleaning)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

TypeError: 'float' object is not callable